### ISSUE TITLE
Ch.3, p.38 to 39 - Note.search scope is case sensitive

### ISSUE THREAD

**Issue by Zhao-Andy** [everydayrails/everydayrails-rspec-2017#7] opened 2017-06-29 21:38 UTC
Not to spam you, but found another slight error.

In `note.rb`, the search scope is case sensitive:
```
  scope :search, ->(term) {
    where("message LIKE ?", "%#{term}%")
  }
```

Which breaks the search term spec, since `note3` has a capital F:
```
    note3 = project.notes.create(
      message: "First, preheat the oven.",
      user: user
    )
```

Perhaps change the scope in `note.rb` to:
```
  scope :search, ->(term) {
    where("LOWER(message) LIKE ?", "%#{term}%")
  }
```

**Comment by ruralocity** [comment] 2017-06-30 12:05
I'm unable to reproduce this using the system-installed version of sqlite3 on MacOS 10.12.5, but I agree that making the search case-insensitive would make it more resilient. I'll change it for the next release, using:

```
scope :search, ->(term) {
  where("LOWER(message) LIKE ?", "%#{term.downcase}%")
}
```

**Comment by Zhao-Andy** [comment] 2017-06-30 16:03
I'm currently running PostgreSQL on MacOS 10.12.1 so that might be the cause of the issue. Thanks for the responses. 👍

**Comment by ruralocity** [comment] 2017-07-11 13:31
Fixed in today's release (July 11, 2017).

**Closed by ruralocity** 2017-07-11 13:31 UTC
Labels: bug, pending release
