### ISSUE TITLE
Ch6 P.105 to P.106 Typo

### ISSUE THREAD

**Issue by dannysiu392005** [everydayrails/everydayrails-rspec-2017#12] opened 2017-06-30 04:55 UTC
The text used as selector should `"RSpec Tutorial"` instead of `"RSpec tutorial"` (capital T), otherwise the test will fail.
i.e. the code should change from
```ruby
require 'rails_helper'

RSpec.feature "Tasks", type: :feature do
  scenario "user toggles a task", js: true do
    user = FactoryGirl.create(:user)
    project = FactoryGirl.create(:project,
      name: "RSpec tutorial",
      owner: user)
    task = project.tasks.create!(name: "Finish RSpec tutorial")

    visit root_path
    click_link "Sign in"
    fill_in "Email", with: user.email
    fill_in "Password", with: user.password
    click_button "Log in"

    click_link "RSpec tutorial"
    check "Finish RSpec tutorial"

    expect(page).to have_css "label#task_#{task.id}.completed"
    expect(task.reload).to be_completed

    uncheck "Finish RSpec tutorial"

    expect(page).to_not have_css "label#task_#{task.id}.completed"
    expect(task.reload).to_not be_completed
  end
end
```

to

```ruby
require 'rails_helper'

RSpec.feature "Tasks", type: :feature do
  scenario "user toggles a task", js: true do
    user = FactoryGirl.create(:user)
    project = FactoryGirl.create(:project,
      name: "RSpec tutorial",
      owner: user)
    task = project.tasks.create!(name: "Finish RSpec tutorial")

    visit root_path
    click_link "Sign in"
    fill_in "Email", with: user.email
    fill_in "Password", with: user.password
    click_button "Log in"

    click_link "RSpec Tutorial"
    check "Finish RSpec tutorial"

    expect(page).to have_css "label#task_#{task.id}.completed"
    expect(task.reload).to be_completed

    uncheck "Finish RSpec tutorial"

    expect(page).to_not have_css "label#task_#{task.id}.completed"
    expect(task.reload).to_not be_completed
  end
end
```

**Comment by ruralocity** [comment] 2017-06-30 12:40
I can't reproduce this, could you check your code again? The project is created with the name "RSpec tutorial" (lowercase t) in both my version and yours, so I would expect the original test to pass. Thanks.

**Comment by dannysiu392005** [comment] 2017-06-30 12:59
Sorry, my mistake, when I was following the book while typing the code, I accidentally typed capital T for the creation of project. That's why I got the test failed.

**Comment by ruralocity** [comment] 2017-06-30 19:44
Thanks for verifying, I'll close this.

**Closed by ruralocity** 2017-06-30 19:44 UTC
Labels: can't reproduce
